disabled = false
locale = "en"
label = "English"
weight = 1
title = "Ikari Shota"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Profile, research notes, and projects by Shota Ikari."

[params.author]
name = "Shota Ikari"
email = "shota-ikari@g.ecc.u-tokyo.ac.jp"
headline = "Master's student at the University of Tokyo."
bio = "Master's student at the University of Tokyo."

[[params.author.links]]
github = "https://github.com/shota-ke"

[[params.author.links]]
linkedin = "https://www.linkedin.com/in/shota-ikari-237168268/"
